Manipulación y limpieza de datos con Python desde fuentes externas.

Contexto: La Cafetería "Café y Código"

Tema lógico: Eres el primer Data Engineer jr de una cafetería de especialidad colombiana. Llevan 4 meses operando 3 sistemas de información completamente desconectados:

-Ventas.csv -> Registro de pedidos, fechas con distintos formatos
-productos.xlsx -> Catálogos y precios, precios nulos, prodcutos duplicados.
-clientes.json -> Una ciudad nula, Un cliente duplicados.

¿Qué es la Ing Datos?

-> Mover datos, tranformar datos, preparar datos, tomar decisiones.

-> El 45% del tiempo de Ingeniero de datos es limpiar y transformar los datos. Es lo que vamos a prender hoy.

¿Qué es Pandas?

No es más que una librería de suma importancia en el mundo de los datos. Cargar, limpiar y analizar datos.

¿Que es Numpy?

Otra libería que nos permite realizar operaciones numéricas de alto rendimiento.

In [1]:
import pandas as pd #Libería para manipular datos tabulares
import numpy as np #Librería para operaciones numéricas

La ingesta de datos.

Es cuando cargamos los archivos para poder leerlos.

In [5]:
#Carga de datos desde CSV
# CSV: Es texto plano donde las columnas está separadas por un delimitador.
# sep = Definir el caracter separador de columnas
# encoding = Define com estan codificados los caracteres. 
# utf-8
# latin1
# cp1252

#Cargamos ventas.csv
df_ventas = pd.read_csv(
    "ventas.csv", 
    sep=',', 
    encoding='utf-8', 
    parse_dates=['fecha']) #Esta columna la interprete como fecha.

df_ventas.head(5)

   id_venta id_producto  cantidad       fecha id_cliente
0         1         P02       1.0  2025-03-23        C18
1         2         P04       2.0  2025-02-01        C07
2         3         P12       5.0  2025-03-28        C06
3         4         P07       1.0  2025-03-17        C02
4         5         P04       2.0  2025-01-12        C33

In [6]:
#Verficar los tipos de datos
df_ventas.dtypes

id_venta         int64
id_producto        str
cantidad       float64
fecha              str
id_cliente         str
dtype: object

### Excel

In [7]:
#sheet_name = Hoja a leer, nombe o indice
#usecols = Columnas a cargar
#skiprows = Filas a saltar al inicio

#Cargar el catalogo de productos desde excel.

df_productos = pd.read_excel(
    "productos.xlsx",
    sheet_name=0 #primera hoja del libro ( indice 0)
)

df_productos

   id_producto      producto categoria   precio
0          P01         Latte    Bebida  12000.0
1          P02     Capuccino    Bebida  11000.0
2          P03      Espresso    Bebida   8000.0
3          P04     Mocaccino    Bebida  13000.0
4          P05       Té chai    Bebida  10000.0
5          P06     Croissant    Comida   9000.0
6          P07       Brownie    Comida   7000.0
7          P08    Cheesecake    Postre  15000.0
8          P09        Muffin    Postre   8000.0
9          P10      Sandwich    Comida  18000.0
10         P11  Jugo natural    Bebida   9500.0
11         P12          Agua    Bebida   4000.0
12         P13      Galletas     Snack   5000.0
13         P14      Empanada     Snack      NaN
14         P15     Café frío    Bebida  14000.0
15         P03      Espresso    Bebida   8000.0

## JSON

JSON es el formato estándar de las APIS y apliaciones web modernas. Toda app móivl, todo servicio en la nube habla json.

In [8]:
#Cargamos los clientes desde el JSON

df_clientes = pd.read_json(
    'clientes.json',
    orient='records', # El json es una lista de objetos [{}, {}, {}, {}] ( el formato má comun en APIS)
    encoding='utf-8' #Para poder soportar tildes y caracteres especiales en nombres.
)

df_clientes.head(10)

  id_cliente                   nombre        ciudad  cliente_frecuente
0        C01   Valentina Ríos Herrera        Bogotá              False
1        C02   Sebastián Muñoz Ospina          Cali              False
2        C03   Mariana Gómez Castillo        Bogotá               True
3        C04     Andrés Felipe Torres      Medellín               True
4        C05   Luisa Fernanda Pedraza  Barranquilla              False
5        C06     Camilo Andrés Vargas          Cali               True
6        C07   Natalia Restrepo Vélez          Cali              False
7        C08    Diego Armando Salcedo           NaN              False
8        C09  Alejandra Mora Quintero      Envigado              False
9        C10     Juan Pablo Echeverri      Medellín               True

### Exploración Inicial de los Datos

### NUNCA TOQUES DATOS QUE NO CONOCES. PRIMERO EXPLORA Y LUEGO TRANSFORMA.

In [9]:
# Auditoria
#Muestrra tipo de datos, cuantos no-nulos hya y memoria usada
#Si cantidad tiene 120 no-nulos de 121 -> hay 1 nulo
df_ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_venta     121 non-null    int64
 1   id_producto  121 non-null    str
 2   cantidad     120 non-null    float64
 3   fecha        121 non-null    str
 4   id_cliente   121 non-null    str
dtypes: float64(1), int64(1), str(3)
memory usage: 6.7 KB

In [10]:
df_ventas.describe() #Nos permite analziar los valores estadisticos descriptivos de los datos

         id_venta    cantidad
count  121.000000  120.000000
mean    60.090909    2.925000
std     34.930884    1.473363
min      1.000000    1.000000
25%     30.000000    2.000000
50%     60.000000    3.000000
75%     90.000000    4.000000
max    120.000000    5.000000

In [14]:
#Exploracion de productos
df_productos.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_producto  16 non-null     str
 1   producto     16 non-null     str
 2   categoria    16 non-null     str
 3   precio       15 non-null     float64
dtypes: float64(1), str(3)
memory usage: 916.0 bytes

In [20]:
#Distribucion de clientes por ciudad
print("Por ciudad: ")
print(df_clientes['ciudad'].value_counts())
print()
print("Frecuentes vs regulares:")
print(df_clientes['cliente_frecuente'].value_counts())

Por ciudad:
ciudad
Cali            10
Envigado         8
Bello            7
Barranquilla     6
Medellín         5
Bogotá           4
Name: count, dtype: int64

Frecuentes vs regulares:
cliente_frecuente
False    25
True     16
Name: count, dtype: int64

In [22]:
#Detectando nulos NaN

#nulos por columna en cada dataset
print("--Ventas--")
print(df_ventas.isna().sum())
print()
print("--Productos--")
print(df_productos.isna().sum())
print()
print("--Clientes--")
print(df_clientes.isna().sum())

--Ventas--
id_venta       0
id_producto    0
cantidad       1
fecha          0
id_cliente     0
dtype: int64

--Productos--
id_producto    0
producto       0
categoria      0
precio         1
dtype: int64

--Clientes--
id_cliente           0
nombre               0
ciudad               1
cliente_frecuente    0
dtype: int64

In [23]:
#Que filas exactamente tiene nulos?
#ventas sin cantidad
df_ventas[df_ventas['cantidad'].isna()]

    id_venta id_producto  cantidad       fecha id_cliente
12        13         P13       NaN  2025-02-03        C30

In [24]:
#Producto sin precio
df_productos[df_productos['precio'].isna()]

   id_producto  producto categoria  precio
13         P14  Empanada     Snack     NaN

In [25]:
#Cliente sin ciudad
df_clientes[df_clientes['ciudad'].isna()]

  id_cliente                 nombre ciudad  cliente_frecuente
7        C08  Diego Armando Salcedo    NaN              False

## Tratando nulos

In [26]:
#Regla de oro: Nunca elimines un nulo sin enteder por qué está ahí!!!!!!!!!!!

#Buena practica: Siempre trabaja sobre una copia para no dañar el archivo orginal

#Creación de copias.
df_ventas_1 = df_ventas.copy()
df_productos_1 = df_productos.copy()
df_clientes_1 = df_clientes.copy()

In [29]:
#Ventas: cantidad nulas --> asumir 1 unidad (minimo logico)

df_ventas_1['cantidad'] = df_ventas_1['cantidad'].fillna(1)

#Convertir a entero ya que las cantidades están como decimales
df_ventas_1['cantidad'] = df_ventas_1['cantidad'].astype(int)

df_ventas_1[df_ventas_1['id_venta'] == df_ventas[df_ventas['cantidad'].isna()]['id_venta'].iloc[0]]

    id_venta id_producto  cantidad       fecha id_cliente
12        13         P13         1  2025-02-03        C30

In [31]:
#Productos: Precio nulos -> imputar con el promedio osea la media

categoria_afectada = df_productos_1[df_productos_1['precio'].isna()]['categoria'].iloc[0]

precio_promedio = df_productos_1[df_productos_1['categoria'] == categoria_afectada]['precio'].mean()

df_productos_1['precio'] = df_productos_1['precio'].fillna(precio_promedio)

#Verify
df_productos_1

   id_producto      producto categoria   precio
0          P01         Latte    Bebida  12000.0
1          P02     Capuccino    Bebida  11000.0
2          P03      Espresso    Bebida   8000.0
3          P04     Mocaccino    Bebida  13000.0
4          P05       Té chai    Bebida  10000.0
5          P06     Croissant    Comida   9000.0
6          P07       Brownie    Comida   7000.0
7          P08    Cheesecake    Postre  15000.0
8          P09        Muffin    Postre   8000.0
9          P10      Sandwich    Comida  18000.0
10         P11  Jugo natural    Bebida   9500.0
11         P12          Agua    Bebida   4000.0
12         P13      Galletas     Snack   5000.0
13         P14      Empanada     Snack   5000.0
14         P15     Café frío    Bebida  14000.0
15         P03      Espresso    Bebida   8000.0

In [ ]:
#Clientes -> ciudad nula ------> marca como 'Ciudad Desconocida'

df_clientes_1['ciudad'] = df_clientes_1['ciudad'].fillna('Ciudad Desconocida')

df_clientes_1[df_clientes_1['id_cliente'] == 'C08']

  id_cliente                 nombre              ciudad  cliente_frecuente
7        C08  Diego Armando Salcedo  Ciudad Desconocida              False

## Duplicados

In [33]:
#Buscamos filas duplicadas
df_productos_1[df_productos_1.duplicated(keep=False)] #Keep false = marca todas las ocurrencias para que podamos verlas

   id_producto  producto categoria  precio
2          P03  Espresso    Bebida  8000.0
15         P03  Espresso    Bebida  8000.0

In [35]:
#Duplicados por id_cliente en clientes
df_clientes_1[df_clientes_1.duplicated(subset=['id_cliente'], keep=False)]

   id_cliente                nombre ciudad  cliente_frecuente
5         C06  Camilo Andrés Vargas   Cali               True
40        C06  Camilo Andrés Vargas   Cali               True

In [36]:
#Eliminación de duplicados productos
df_productos_1 = df_productos_1.drop_duplicates(keep='first').reset_index(drop=True)

#Clientes.
df_clientes_1 = df_clientes_1.drop_duplicates(subset=['id_cliente'], keep='first').reset_index(drop=True)

print(f"Productos: {len(df_productos)} -> {len(df_productos_1)} filas")
print(f"Clientes: {len(df_clientes)} -> {len(df_clientes_1)} filas")

Productos: 16 -> 15 filas
Clientes: 41 -> 40 filas